export const GET_PRODUCTS_FETCHING = 'GET_PRODUCTS_FETCHING';
export const GET_PRODUCTS_FULFILLED = 'GET_PRODUCTS_FULFILLED';
export const GET_PRODUCTS_REJECTED = 'GET_PRODUCTS_REJECTED';

export const ADD_PRODUCTS_FETCHING = 'ADD_PRODUCTS_FETCHING';
export const ADD_PRODUCTS_FULFILLED = 'ADD_PRODUCTS_FULFILLED';
export const ADD_PRODUCTS_REJECTED = 'ADD_PRODUCTS_REJECTED';

export const DELETE_PRODUCTS_FETCHING = 'DELETE_PRODUCTS_FETCHING';
export const DELETE_PRODUCTS_FULFILLED = 'DELETE_PRODUCTS_FULFILLED';
export const DELETE_PRODUCTS_REJECTED = 'DELETE_PRODUCTS_REJECTED';

export const UPDATE_PRODUCTS_FETCHING = 'UPDATE_PRODUCTS_FETCHING';
export const UPDATE_PRODUCTS_FULFILLED = 'UPDATE_PRODUCTS_FULFILLED';
export const UPDATE_PRODUCTS_REJECTED = 'UPDATE_PRODUCTS_REJECTED';

export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';